name: Release
on: [workflow_dispatch]

jobs:
  versions:
    name: Get versions
    runs-on: ubuntu-latest
    outputs:
      current-version: ${{ steps.previous-tag.outputs.tag }}
      next-version: ${{ steps.sem-version.outputs.patch }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Get Previous tag'
        id: previous-tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.2

      - name: 'Get next minor version'
        id: sem-version
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previous-tag.outputs.tag }}

      - name: Print versions
        run: 'echo "Current version: ${{ steps.previous-tag.outputs.tag }}, next version: ${{ steps.sem-version.outputs.patch }}"'

  build-and-publish:
    name: Build and publish
    runs-on: windows-latest
    needs: versions
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.200

      - name: Build
        run: dotnet build --configuration Release /p:Version=${{ needs.versions.outputs.next-version }}

      - name: Test
        run: dotnet test --configuration Release /p:Version=${{ needs.versions.outputs.next-version }} --no-build

      - name: Pack
        run: dotnet pack --configuration Release /p:Version=${{ needs.versions.outputs.next-version }} --no-build --output .

      - name: Publish Agent Framework Dependant
        run: dotnet publish ResurrectedTrade.Agent/ResurrectedTrade.Agent.csproj --configuration Release --no-self-contained --no-build --output out

      - name: Move framework dependant
        run: Move-Item out/ResurrectedTrade.exe out/ResurrectedTrade-FrameworkDependant.exe

      - name: Publish Agent Self-Contained
        run: dotnet publish ResurrectedTrade.Agent/ResurrectedTrade.Agent.csproj --configuration Release /p:DefineConstants=SELF_CONTAINED --self-contained --no-build --output out

      - name: Move self contained
        run: Move-Item out/ResurrectedTrade.exe out/ResurrectedTrade-SelfContained.exe

      - name: Sign Agent binaries
        uses: InertiaSystems/code-sign-action@v1.1.0
        with:
          certificate: ${{ secrets.SIGNING_CERTIFICATE }}
          description: 'Resurrected Trade Agent ${{ needs.versions.outputs.next-version }}'
          password: ${{ secrets.SIGNING_CERTIFICATE_PASSWORD }}
          certificatesha1: ${{ secrets.SIGNING_CERTIFICATE_FINGERPRINT }}
          certificatename: ${{ secrets.SIGNING_CERTIFICATE_NAME }}
          timestampUrl: http://timestamp.digicert.com
          folder: out
          recursive: false

      - uses: actions/upload-artifact@v2
        with:
          name: ResurrectedTrade Agent ${{ needs.versions.outputs.next-version }}
          if-no-files-found: error
          path: |
            out/ResurrectedTrade-SelfContained.exe
            out/ResurrectedTrade-FrameworkDependant.exe

      - uses: actions/upload-artifact@v2
        with:
          name: ResurrectedTrade NuGet Packages ${{ needs.versions.outputs.next-version }}
          if-no-files-found: error
          path: |
            ResurrectedTrade.Common.${{ needs.versions.outputs.next-version }}.nupkg
            ResurrectedTrade.AgentBase.${{ needs.versions.outputs.next-version }}.nupkg

  tag-and-upload:
    name: Tag and upload assets
    runs-on: ubuntu-latest
    needs: [versions, build-and-publish]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.200

      - uses: actions/download-artifact@v3

      - uses: rickstaa/action-create-tag@v1
        with:
          tag: v${{ needs.versions.outputs.next-version }}

      - name: Push Common
        run: dotnet nuget push "ResurrectedTrade NuGet Packages ${{ needs.versions.outputs.next-version }}/ResurrectedTrade.Common.${{ needs.versions.outputs.next-version }}.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_TOKEN }} --skip-duplicate

      - name: Push Agent Base
        run: dotnet nuget push "ResurrectedTrade NuGet Packages ${{ needs.versions.outputs.next-version }}/ResurrectedTrade.AgentBase.${{ needs.versions.outputs.next-version }}.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_TOKEN }} --skip-duplicate

      - name: Upload assets to github
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ needs.versions.outputs.next-version }}
          fail_on_unmatched_files: true
          files: |
            ResurrectedTrade Agent ${{ needs.versions.outputs.next-version }}/ResurrectedTrade-SelfContained.exe
            ResurrectedTrade Agent ${{ needs.versions.outputs.next-version }}/ResurrectedTrade-FrameworkDependant.exe
            ResurrectedTrade NuGet Packages ${{ needs.versions.outputs.next-version }}/ResurrectedTrade.Common.${{ needs.versions.outputs.next-version }}.nupkg
            ResurrectedTrade NuGet Packages ${{ needs.versions.outputs.next-version }}/ResurrectedTrade.AgentBase.${{ needs.versions.outputs.next-version }}.nupkg
