name: Publish to nuget
on:
  push:
    branches:
      - main # Default release branch, may also be named 'master' or 'develop'
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.200
      
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.2

      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - name: Build
        run: dotnet build --configuration Release /p:Version=${{ steps.semvers.outputs.patch }}

      - name: Test
        run: dotnet test --configuration Release /p:Version=${{ steps.semvers.outputs.patch }} --no-build

      - name: Pack
        run: dotnet pack --configuration Release /p:Version=${{ steps.semvers.outputs.patch }} --no-build --output .

      - name: Push
        run: dotnet nuget push *.nupkg --source https://nuget.pkg.github.com/acraven/index.json --api-key ${{ secrets.NUGET_API_TOKEN }} --skip-duplicate

      - uses: rickstaa/action-create-tag@v1
        with:
          tag: v${{ steps.semvers.outputs.patch }}
